# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_pwd',
            name='password',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='user_pwd',
            name='user',
            field=models.CharField(max_length=2000),
        ),
    ]
