# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-09 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180409_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_pwd',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_pwd',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
